### ISSUE TITLE
Adding a single word to a signal by double clicking highlights but is not saved

### ISSUE THREAD

**Issue by amir-zeldes** [amir-zeldes/rstWeb#63]
To reproduce:

  * Create a new signal
  * Highlight a single word by double clicking it (not dragging). The word will be highlighted, suggesting an annotation has been added
  * Hit save to close the tray
  * The signal will be saved, but the highlighted token will not

**Comment by lgessler** [comment]
This should be fixed now, let me know if it's still happening
