### ISSUE TITLE
Consider color-coding token highlights by signal type on hover

### ISSUE THREAD

**Issue by lgessler** [amir-zeldes/rstWeb#67]
For signals, user gave feedback that it would be nice to color token highlights by type (+ subtype?). E.g., genre = green highlight, DM = yellow highlight, etc. 

Solution isn't obvious because we expect token highlights to overlap often. In case of overlap, do colors mix, does the last-applied one win, do we use a "mixed" color...?

**Comment by amir-zeldes** [comment]
Implemented in V4.0.0
