### ISSUE TITLE
Custom Relation Set?

### ISSUE THREAD

**Issue by mohamadi-sara20** [amir-zeldes/rstWeb#77]
Hi, 
is there any possibility to define a custom relation set? I don't seem to find this.

**Comment by lgessler** [comment]
Hi, you can do that by editing [the TSV](https://github.com/amir-zeldes/rstWeb/blob/4d3125ebb13fc6e50719cc43f34f795af3b21cbb/users/default_rels.tab)

**Comment by mohamadi-sara20** [comment]
I closed this. But  just as a suggestion, I think it'd be useful to allow defining custom relations in the user interface.
