### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mohamadi-sara20** [amir-zeldes/rstWeb#78]
Hi, 
I have seen this happen a few times, though I don't really think I have done anything unnatural in annotating and believe this should not happen. 
For example, when I try to edit my segmentation and move a segment boundary, this happens. 
When I try to upload a file rstweb itself has given me, I encounter this. 
<img width="1041" alt="Screen Shot 2020-01-27 at 12 32 21 PM" src="https://user-images.githubusercontent.com/32369115/73161672-4fee2000-4101-11ea-9660-e1ef7a413c8f.png">

Is this the expected/known behavior?

**Comment by amir-zeldes** [comment]
This looks like a bug - I see you're using the local version on Python 2.7 on a Mac, is that right? Can you give me a minimal example with step by step instructions to recreate the problem?

**Comment by mohamadi-sara20** [comment]
I have not encountered this error since I created this issue. Yes, I am using the app on Mac with python 2.7. I will try to come up with reproduction steps of the error but no luck so far. So I guess we could close this until I figure out how to reproduce the error. 
Thanks!

**Comment by amir-zeldes** [comment]
OK, thanks for reporting - if you can reproduce it please reopen the issue.
