### ISSUE TITLE
I want to know, is it a display tool or rst parser tool?

### ISSUE THREAD

**Issue by wangwang110** [amir-zeldes/rstWeb#88]

**Comment by arne-cl** [comment]
Dear @wangwang110 rstWeb is not a parser, but an annotation tool for RST and can also be used for visualizing RST trees.

**Comment by amir-zeldes** [comment]
Thansk @arne-cl , yes, that's right - it is meant for creating and editing gold standard corpora, which can be used for training parsers, but it is not a parser in itself. It might be nice to include some pretrained parsing models to give an initial tree to imported plain text data, but that is not currently supported.
